name: CI Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Specify the Python version you need

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: |
        python setup.py install

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x.x' # Specify the .NET version you need

    - name: Restore dependencies
      run: dotnet restore open-simulation-interface-csharp.csproj

    - name: Build
      run: dotnet build --configuration Release open-simulation-interface-csharp.csproj

    - name: Pack NuGet package
      run: dotnet pack --configuration Release --output ./nupkgs open-simulation-interface-csharp.csproj

    - name: Publish NuGet package
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }} # Set this secret in your repository settings
      run: |
        dotnet nuget push "./nupkgs/*.nupkg" --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
