name: CI Trigger

on:
  #workflow_dispatch:
  release:
    types: [published]

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  build:
    needs: setup
    uses: ./.github/workflows/build.yml

  nuget:
    needs: build
    uses: ./.github/workflows/nuget.yml

  release:
    #if: github.event_name == 'release'
    needs: nuget
    uses: ./.github/workflows/release.yml
